version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      # TODO: Remove
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olive
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning

  server:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    # TODO: Remove
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
